// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchDiscordBot.Data;

#nullable disable

namespace TwitchDiscordBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221018194811_new-start")]
    partial class newstart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TwitchDiscordBot.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Messagecount")
                        .HasColumnType("int");

                    b.Property<int?>("UserCommandId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCommandId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TwitchDiscordBot.Entities.UserCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Insult")
                        .HasColumnType("bit");

                    b.Property<bool>("TranslateDoge")
                        .HasColumnType("bit");

                    b.Property<bool>("TranslateYoda")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserCommand");
                });

            modelBuilder.Entity("TwitchDiscordBot.Entities.User", b =>
                {
                    b.HasOne("TwitchDiscordBot.Entities.UserCommand", "UserCommand")
                        .WithMany()
                        .HasForeignKey("UserCommandId");

                    b.Navigation("UserCommand");
                });
#pragma warning restore 612, 618
        }
    }
}
